name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
          
      - name: Navigate to wilds directory
        run: cd wilds
          
      - name: Install Dependencies
        working-directory: ./wilds
        run: pnpm install
        
      - name: Build
        working-directory: ./wilds
        run: pnpm build
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: wilds/dist
          branch: gh-pages 